# Menghitung Count Perawi sebagai Guru dan Murid

## Import Library

In [1]:
import pandas as pd
import re

In [2]:
# pd.set_option('display.max_colwidth', None)

df = pd.read_csv('../data/processed/edges.csv', header=None)
df.columns = ['Guru', 'Murid', 'Weight', 'Inverse_Weight']
df = df.iloc[1:].reset_index(drop=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12852\4147847548.py:3: DtypeWarning: Columns (0: 2, 1: 3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/processed/edges.csv', header=None)

In [3]:
display(df)

,Guru,Murid,Weight,Inverse_Weight
0,جابر بن زيد الازدي,ابو عبيدة مسلم بن ابو كريمة التميمي,1,1.0
1,عبد الله بن عباس,جابر بن زيد الازدي,1,1.0
2,جابر بن زيد,ابو عبيدة,522,0.0019157088122605363
3,عائشة,جابر بن زيد,68,0.014705882352941176
4,ابو هريرة,جابر بن زيد,76,0.013157894736842105
...,...,...,...,...
776990,ابي مسعود البدري,حذيفة بن اليمان,1,1.0
776991,سعيد بن العاص,ابي مسعود البدري,1,1.0
776992,ابو مسعود,سعيد بن العاص,1,1.0
776993,عبد الله,علي بن علقمة,1,1.0
776994,لانس بن مالك,العلاء بن زياد,1,1.0

In [4]:
edges_df = df[['Guru', 'Murid']].copy()

# Ambil semua nama perawi dari Guru dan Murid
semua_perawi = pd.concat([
    edges_df['Guru'],
    edges_df['Murid']
]).drop_duplicates().reset_index(drop=True)

# Buat DataFrame perawi
perawi_stats = pd.DataFrame({
    'Perawi': semua_perawi
})

# Hitung jumlah sebagai Guru
perawi_stats['Jumlah_Sebagai_Guru'] = (
    perawi_stats['Perawi']
    .map(edges_df['Guru'].value_counts())
    .fillna(0)
    .astype(int)
)

# Hitung jumlah sebagai Murid
perawi_stats['Jumlah_Sebagai_Murid'] = (
    perawi_stats['Perawi']
    .map(edges_df['Murid'].value_counts())
    .fillna(0)
    .astype(int)
)

# Tampilkan hasil
display(perawi_stats)

,Perawi,Jumlah_Sebagai_Guru,Jumlah_Sebagai_Murid
0,جابر بن زيد الازدي,1,1
1,عبد الله بن عباس,405,134
2,جابر بن زيد,47,74
3,عائشة,2334,733
4,ابو هريرة,3529,1287
...,...,...,...
177381,عبد الرحمن بن الاسود بن عامر شاذان,0,1
177382,احمد بن عمران الاحمسي,0,1
177383,الحمدي,0,1
177384,عمرو بن خالد القرشي,0,1
177385,عمرو بن قرة,0,1